GET http://localhost:5000/api/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MDUwZGQzM2RiMzkwOTNhNzE5Zjk3ZCIsIm5hbWUiOiJBZG1pbiIsInVzZXJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwiY291bnRyeSI6IklUQSIsImdlbmRlciI6Im1hbGUiLCJiaXJ0aERhdGUiOiIyMDI0LTEwLTA4VDEwOjQ3OjQ3LjUxNFoiLCJwZXJtaXNzaW9ucyI6WyJhZG1pbiJdLCJpYXQiOjE3MjgzOTUyODcsImV4cCI6MTcyODM5ODg4N30.8lmzfxlnWpbpz_e9tE8LimKkyKDHSEjbV1_KRc4g6nY

###
GET http://localhost:5000/api/user/66facd5f967fe5ba32daf584
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MDUxM2RhOTVjMDMwNWE1MDdkNGI0YyIsIm5hbWUiOiJUZXJlemEiLCJ1c2VybmFtZSI6InRlcmV6YSIsImVtYWlsIjoidGV0ZUBleGFtcGxlLmNvbSIsImNvdW50cnkiOiJJVEEiLCJnZW5kZXIiOiJmZW1hbGUiLCJiaXJ0aERhdGUiOiIxOTkwLTAxLTAxVDAwOjAwOjAwLjAwMFoiLCJwZXJtaXNzaW9ucyI6WyJyZWFkIiwid3JpdGUiXSwiaWF0IjoxNzI4Mzk1MjY0LCJleHAiOjE3MjgzOTg4NjR9.tyc9NGXKyrPoTPGSRGZBwO3EBzGKBOix2qnbkWsJYFg

###
GET http://localhost:5000/api/user/email/john.doe@example.com

###
GET http://localhost:5000/api/user/username/johndoe

###
POST http://localhost:5000/api/user/login
Content-Type: application/json

{
    "username": "admin",
    "password": "admin123"
}

###
POST http://localhost:5000/api/user/register
Content-Type: application/json

{
    "name": "Tereza",
    "username": "tereza",
    "email": "tete@example.com",
    "gender": "female",
    "country": "ITA",
    "birthDate": "1990-01-01",
    "password": "tereza123",
    "permissions": []
}

###
PUT http://localhost:5000/api/user/update/66facd5f967fe5ba32daf584
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZmFjZDVmOTY3ZmU1YmEzMmRhZjU4NCIsIm5hbWUiOiJHdWlsaGVybWUiLCJ1c2VybmFtZSI6Imd1aWxoIiwiZW1haWwiOiJ0ZXN0LmFybWFuaUBleGFtcGxlLmNvbSIsImNvdW50cnkiOiJJVEEiLCJnZW5kZXIiOiJtYWxlIiwiYmlydGhEYXRlIjoiMTk5MC0wMS0wMVQwMDowMDowMC4wMDBaIiwicGVybWlzc2lvbnMiOlsicmVhZCIsIndyaXRlIl0sImlhdCI6MTcyNzc3NDM2NywiZXhwIjoxNzI3Nzc3OTY3fQ.elv6oYAKJ2arY8sY4gRux5Phou79b6M_o0IRx5DrTqI
Content-Type: application/json

{
    "name": "Guilherme Seletti",
    "username": "guilh",
    "email": "test.armani@example.com",
    "gender": "male",
    "country": "ITA",
    "birthDate": "1990-01-01",
    "password": "password555"
}

###
DELETE http://localhost:5000/api/user/delete/67050dd33db39093a719f97d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MDUwZGQzM2RiMzkwOTNhNzE5Zjk3ZCIsIm5hbWUiOiJBZG1pbiIsInVzZXJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwiY291bnRyeSI6IklUQSIsImdlbmRlciI6Im1hbGUiLCJiaXJ0aERhdGUiOiIyMDI0LTEwLTA4VDEwOjQ3OjQ3LjUxNFoiLCJwZXJtaXNzaW9ucyI6WyJhZG1pbiJdLCJpYXQiOjE3MjgzOTUyODcsImV4cCI6MTcyODM5ODg4N30.8lmzfxlnWpbpz_e9tE8LimKkyKDHSEjbV1_KRc4g6nY

