GET http://localhost:5000/api/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZmFjNzEwOTY3MTNiNzQ0MjhjYWIzMiIsIm5hbWUiOiJHdWlsaGVybWUgU2VsZXR0aSIsInVzZXJuYW1lIjoiZ3VpIiwiZW1haWwiOiJncG9zLmFybWFuaUBleGFtcGxlLmNvbSIsImNvdW50cnkiOiJJVEEiLCJnZW5kZXIiOiJtYWxlIiwiYmlydGhEYXRlIjoiMTk5MC0wMS0wMVQwMDowMDowMC4wMDBaIiwicGVybWlzc2lvbnMiOlsicmVhZCIsIndyaXRlIl0sImlhdCI6MTcyNzc3MTUxMCwiZXhwIjoxNzI3Nzc1MTEwfQ.IkGTzPfek0P9lSS5W4vyP_ze7l1x4hAnfX1-NENIo4o

###
GET http://localhost:5000/api/user/66fac71096713b74428cab32
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZmFjNzEwOTY3MTNiNzQ0MjhjYWIzMiIsIm5hbWUiOiJHdWlsaGVybWUgU2VsZXR0aSIsInVzZXJuYW1lIjoiZ3VpIiwiZW1haWwiOiJncG9zLmFybWFuaUBleGFtcGxlLmNvbSIsImNvdW50cnkiOiJJVEEiLCJnZW5kZXIiOiJtYWxlIiwiYmlydGhEYXRlIjoiMTk5MC0wMS0wMVQwMDowMDowMC4wMDBaIiwicGVybWlzc2lvbnMiOlsicmVhZCIsIndyaXRlIl0sImlhdCI6MTcyNzc3MTUxMCwiZXhwIjoxNzI3Nzc1MTEwfQ.IkGTzPfek0P9lSS5W4vyP_ze7l1x4hAnfX1-NENIo4o

###
GET http://localhost:5000/api/user/email/john.doe@example.com

###
GET http://localhost:5000/api/user/username/johndoe

###
POST http://localhost:5000/api/user/login
Content-Type: application/json

{
    "username": "guilh",
    "password": "password555"
}

###
POST http://localhost:5000/api/user/register
Content-Type: application/json

{
    "name": "Guilherme",
    "username": "gui",
    "email": "test.armani@example.com",
    "gender": "male",
    "country": "ITA",
    "birthDate": "1990-01-01",
    "password": "password555"
}


###
PUT http://localhost:5000/api/user/update/66facd5f967fe5ba32daf584
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZmFjZDVmOTY3ZmU1YmEzMmRhZjU4NCIsIm5hbWUiOiJHdWlsaGVybWUiLCJ1c2VybmFtZSI6Imd1aWxoIiwiZW1haWwiOiJ0ZXN0LmFybWFuaUBleGFtcGxlLmNvbSIsImNvdW50cnkiOiJJVEEiLCJnZW5kZXIiOiJtYWxlIiwiYmlydGhEYXRlIjoiMTk5MC0wMS0wMVQwMDowMDowMC4wMDBaIiwicGVybWlzc2lvbnMiOlsicmVhZCIsIndyaXRlIl0sImlhdCI6MTcyNzc3NDM2NywiZXhwIjoxNzI3Nzc3OTY3fQ.elv6oYAKJ2arY8sY4gRux5Phou79b6M_o0IRx5DrTqI
Content-Type: application/json

{
    "name": "Guilherme Seletti",
    "username": "guilh",
    "email": "test.armani@example.com",
    "gender": "male",
    "country": "ITA",
    "birthDate": "1990-01-01",
    "password": "password555"
}

###
DELETE http://localhost:5000/api/user/delete/66f407176432b3c398cd7b39