GET http://localhost:5000/api/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZmFjZDVmOTY3ZmU1YmEzMmRhZjU4NCIsInVzZXJuYW1lIjoiZ3VpbGgiLCJpYXQiOjE3Mjc3MjM0MTEsImV4cCI6MTcyNzcyNzAxMX0.wJzw3KmKv9ndFX_uyQo9ilIoVYpltvYyYTNGlkRkCuU


###
GET http://localhost:5000/api/user/66facd5f967fe5ba32daf584

###
GET http://localhost:5000/api/user/email/john.doe@example.com

###
GET http://localhost:5000/api/user/username/johndoe

###
POST http://localhost:5000/api/user/login
Content-Type: application/json

{
    "username": "guilh",
    "password": "password555"
}

###
POST http://localhost:5000/api/user/register
Content-Type: application/json

{
    "name": "Guilherme",
    "username": "guilh",
    "email": "test.armani@example.com",
    "gender": "male",
    "country": "ITA",
    "birthDate": "1990-01-01",
    "password": "password555"
}


###
PUT http://localhost:5000/api/user/update/66f407176432b3c398cd7b39
Content-Type: application/json

{
    "name": "John Doe",
    "username": "johndoe",
    "email": "john.doe@example.com",
    "gender": "male",
    "country": "USA",
    "birthDate": "1990-01-01",
    "password": "password1234"
}

###
DELETE http://localhost:5000/api/user/delete/66f407176432b3c398cd7b39